# Generated by Django 4.1 on 2023-01-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usrName", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("quote", models.TextField()),
                ("quotedAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
