# Generated by Django 4.1 on 2023-01-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addedAt", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(max_length=255)),
                ("title", models.TextField()),
                ("diary_content", models.TextField()),
            ],
        ),
    ]
